Created my dev folder and file
JohnMurwin/NaturalSelectionSimulation pull request #16
Opened 2022-01-29 07:59 UTC by Tiberious

## Description

## Checklist

### Pre-PR
- [ ] Merge #dev into a testing branch and verify no conflicts present
- [ ] Project Items conform to the Style Guide
- [ ] Pull Request target branch is NOT #main (these types of PRs are handled by Project Admins)

### Post-PR
Once the pull request is created, make sure to do the following:
- [ ] Request a reviewer
- [ ] Comment if Branch can be deleted once closed

## Context

## How Has This Been Tested?

## Screenshots (if appropriate):

2022-01-29 08:00 UTC, Tiberious commented
Can be deleted once closed

2022-02-02 13:53 UTC, JohnMurwin requested changes

2022-02-02 13:53 UTC, JohnMurwin commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/DEV_Brett.cs
> +    void Update()
Remove empty unused method.

2022-02-05 02:28 UTC, JohnMurwin approved these changes

2022-02-05 02:28 UTC, merged