#NSSI-87 Main free fly x-y-z camera
JohnMurwin/NaturalSelectionSimulation pull request #22
Opened 2022-02-12 01:28 UTC by Tiberious

## Description

Allows the camera to fly up and down and back and forth using "w,a,s,d" buttons

## Checklist

### Pre-PR
- [X ] Merge #dev into a testing branch and verify no conflicts present
- [X ] Project Items conform to the Style Guide
- [X ] Pull Request target branch is NOT #main (these types of PRs are handled by Project Admins)

### Post-PR
Once the pull request is created, make sure to do the following:
- [X] Request a reviewer
- [X] Comment if Branch can be deleted once closed

## Context

## How Has This Been Tested?

## Screenshots (if appropriate):

2022-02-13 00:57 UTC, JohnMurwin requested changes
Couple of things to fix. You should also make this a Prefab object that can be placed onto a camera (or make a camera prefab yourself). 

Also your PR doesnt contain all of the functions that your camera script does? So make sure you to update your PR information accordingly.

2022-02-13 00:57 UTC, JohnMurwin commented on NaturalSelectionSimulation/.vsconfig
> +﻿{
This file should not be included & removed from commit. (this will be fixed in latest major update so for now remove)

2022-02-13 00:57 UTC, JohnMurwin commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +
Need the namespace: NaturalSelectionSimulation

2022-02-13 00:57 UTC, JohnMurwin commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +	public float acceleration = 50; // how fast you accelerate
All of these variables should most likely be Private, don't see any reason to make them public. Use the variable attribute: [SerializeField] to make Private/Protected fields accessible in Editor. Private variables also share the `_cameCase` type.

2022-02-13 00:57 UTC, JohnMurwin commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +	public float accSprintMultiplier = 4; // how much faster you go when "sprinting"
Probably should change your stock text to what we are actually doing lol. We arent sprinting.

2022-02-13 00:57 UTC, JohnMurwin commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +	public float dampingCoefficient = 5; // how quickly you break to a halt after you stop your input
These two should probably remain public so we can tweak them in the settings.

2022-02-13 00:57 UTC, JohnMurwin commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +			Cursor.visible = value == false;
For now this is probably okay? But you should set this to a parameter as later on we want to see our cursor to select animals.

2022-02-13 00:57 UTC, JohnMurwin commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +		return direction * acceleration; // "walking"
Once again, should probably double check your code for bad comments lol.

2022-02-13 00:57 UTC, JohnMurwin commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +		else if( Input.GetMouseButtonDown( 0 ) )
This comment goes for all of your inputs: Normally, I would say you want to paramertize this more as if we ever decide to change the 'Focused' key, all of this code would change (hence where the NewInputSystem comes into play); HOWEVER as this is a short term project this is fine, but something to think about.

2022-02-13 06:15 UTC, Tiberious commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +	public float dampingCoefficient = 5; // how quickly you break to a halt after you stop your input
left public

2022-02-13 06:15 UTC, Tiberious commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +	public float accSprintMultiplier = 4; // how much faster you go when "sprinting"
got rid of sprinting, don't need this

2022-02-13 06:17 UTC, Tiberious commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +	public float acceleration = 50; // how fast you accelerate
Don't quite understand this comment. I made a change to the variable that should be private. Let me know if I need to do anything more

2022-02-13 06:20 UTC, Tiberious commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +
added the namespace

2022-02-13 06:52 UTC, Tiberious commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +		else if( Input.GetMouseButtonDown( 0 ) )
made more of the hardcoded values variables to be set

2022-02-13 07:18 UTC, Tiberious commented on NaturalSelectionSimulation/Assets/NaturalSelectionSimulation/_Dev/DevBrett/FlyCam.cs
> +			Cursor.visible = value == false;
changed this part up a bit

2022-02-13 07:25 UTC, Tiberious commented on NaturalSelectionSimulation/.vsconfig
> +﻿{
removed

2022-02-18 02:03 UTC, JohnMurwin approved these changes
LGTM

2022-02-18 02:04 UTC, merged